### ISSUE TITLE
Move docs for user-defined rules to a separate page

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#427]
## Details

Currently, user-defined rules are documented on the `normalizer transform` page ([link](https://www.objectionary.com/normalizer/docs/normalizer/transform.html#yegoryaml)).

However, these rules are used in the `normalizer dataize` command too.

Hence, we need to provide a comprehensive documentation for user-defined rules on a separate page.

## Subtasks

- [x] Describe the YAML format
- [ ] Describe the syntax of each string input (e.g., the pattern must be an object)
- [ ] Explain how to write user-defined rules
- [ ] Explain conditions
- [ ] Add custom rules implemented in https://github.com/objectionary/normalizer/pull/432
