### ISSUE TITLE
Speed up stack setup in CI

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#508]
## Details

Currently, during the `Setup Stack` step, the `eo-phi-normalizer` is built from scratch.

https://github.com/objectionary/eo-phi-normalizer/actions/runs/11260821782/job/31312900571#step:6:70

For some reason, the `.cabal` file is modified.

https://github.com/objectionary/eo-phi-normalizer/actions/runs/11260821782/job/31312900571#step:6:191

## Subtasks

- [ ] Learn why `.cabal` is modified
- [ ] Prevent modifications
- [ ] Generate a new cache
- [ ] Check whether there's a speedup
