### ISSUE TITLE
Make markdown generation reproducible

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#512]
## Details

Currently, we commit changes in site files on PR branches. The output of some commands that produce changes may differ between workflow runs. Hence, if we run CI on the `master` branch, CI tries to commit changes and fails.

We should make the output of commands completely controllable so that there are no changes to commit when running CI on `master`.

The problematic commands are described in the sections below.

### Command 1 - get Java tooling versions

https://github.com/objectionary/eo-phi-normalizer/actions/runs/11371427995/job/31633491462#step:21:13

The cause is that the Java version isn't fixed in the workflow file.

https://github.com/objectionary/eo-phi-normalizer/blob/500b2517beda23aa36f7c79667c3678219ef60ef/.github/workflows/ghc.yml#L168

### Command 2 - the `test` command

The command may report different time.

https://github.com/objectionary/eo-phi-normalizer/pull/513/commits/c29231f85a640dd88a4f2570eaaee8ca29bce552#diff-c6cc0cdc9ab2083dc0096dba6b67cf01609ad28c431377563b0ec4b241c6a5d3R71

### Command 3 - `node --version`

The `node` version may change in future, so it also should be fixed.

https://github.com/objectionary/eo-phi-normalizer/blob/f5b129547ccd3db220029f4352926968fbcdc967/.github/workflows/ghc.yml#L162

## Subtasks

- [x] Use java 21.0.5+11 in CI (#513)
- [x] Output the same time for the `test` command (#513)
- [ ] Use node 20.18.0 in CI

**Comment by 0crat** [comment]
@deemp Thank you for your contribution! While this ticket wasn't accepted, your effort is valuable. You've earned -16 points, bringing your balance to [-4](https://www.eolang.org/zerocracy/objectionary-vitals.html). Remember, every report helps improve our project. Stay positive and [keep reporting](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) bugs or suggesting enhancements. For future submissions, check out our guide on [how to report bugs effectively](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html). Your dedication is appreciated! 💪
