### ISSUE TITLE
Derive stream transformation rules

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#530]
## Details 

From https://github.com/objectionary/eo-phi-normalizer/issues/470#issuecomment-2451785590

## Subtasks

1. [ ] Convert to PHI:
   - Java code with `map`
   - Java code without `map`
1. [ ] Convert bytes in PHI to text
1. [ ] Find pattern that corresponds to `map`
1. [ ] Write a rule that transforms that `map`
