### ISSUE TITLE
Annotate files with a copyright notice

### ISSUE THREAD

**Issue by deemp** [objectionary/eo-phi-normalizer#535]
## Details

The #534 introduced a CI job that checks copyright notices in multiple files.

This job fails if some notices are missing or incorrect.

We need that files that the job checks to be annotated with copyright notices so that the job doesn't fail.

Here's the [list of files](https://github.com/objectionary/eo-phi-normalizer/actions/runs/11854247531/job/33036014508?pr=534#step:3:176) that currently cause errors.

## Subtasks

- [ ] Add copyright notices in the files that cause errors
- [x] Update [this function](https://github.com/objectionary/eo-phi-normalizer/blob/c53ed6a49b5632c4eed7cc347d1fb3bfc1f7361e/scripts/pipeline.sh#L38) so that it additionally inserts copyright notices into `.phi` files after [copying](https://github.com/objectionary/eo-phi-normalizer/blob/c53ed6a49b5632c4eed7cc347d1fb3bfc1f7361e/scripts/pipeline.sh#L48) the files. It's necessary for [these generated files](https://github.com/objectionary/eo-phi-normalizer/actions/runs/11854247531/job/33036014508?pr=534#step:3:73). UPD: we don't need to insert comments into `.phi` files - see https://github.com/objectionary/eo-phi-normalizer/issues/450#issuecomment-2478540817.
- [ ] Learn which license should files generated by BNFC have.
- [ ] If the license required by BNFC is different from [LICENSE.txt](https://github.com/objectionary/eo-phi-normalizer/blob/c53ed6a49b5632c4eed7cc347d1fb3bfc1f7361e/LICENSE.txt), create another step in the `copyright` job https://github.com/objectionary/eo-phi-normalizer/pull/534. This step should check the license required by BNFC specifically in `Print.hs` and `Abs.hs`. Don't check these files against `LICENSE.txt`.
- [ ] Update the script in `Setup.hs` so that after running BNFC it reads the appropriate license file and inserts the copyright notice in [Print.hs and Abs.hs](https://github.com/objectionary/eo-phi-normalizer/actions/runs/11854247531/job/33036014508?pr=534#step:3:48). Ensure the license file is in the `eo-phi-normalizer` directory and is specified in [extra-source-files](https://github.com/objectionary/eo-phi-normalizer/blob/c53ed6a49b5632c4eed7cc347d1fb3bfc1f7361e/eo-phi-normalizer/package.yaml#L10).
